name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change as per your runtime

    - name: Install dependencies
      run: npm install

    - name: Package Lambda
      run: cd terraform && zip -r lambda.zip ../lambda/*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Deploy with Terraform
      run: |
        cd terraform &&
        terraform init
        terraform plan -out=plan.tfplan
        terraform apply -auto-approve plan.tfplan
        terraform destroy